const database = {
    brasil:{
        // --- ELITE (SÉRIE A) ---
        serieA: [
            { nome: "Flamengo", forca: 85, escudo: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Flamengo_braz_logo.svg", orcamento: "R$ 1.2 Bi" },
            { nome: "Palmeiras", forca: 84, escudo: "https://upload.wikimedia.org/wikipedia/commons/1/10/Palmeiras_logo.svg", orcamento: "R$ 1 Bi" },
            { nome: "Botafogo", forca: 83, escudo: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Escudo_Botafogo.png", orcamento: "R$ 900 Mi" },
            { nome: "Atlético-MG", forca: 82, escudo: "https://upload.wikimedia.org/wikipedia/commons/2/27/Club_Atl%C3%A9tico_Mineiro_-_Escudo.png", orcamento: "R$ 800 Mi" },
            { nome: "São Paulo", forca: 80, escudo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Brasao_do_Sao_Paulo_Futebol_Clube.svg/1200px-Brasao_do_Sao_Paulo_Futebol_Clube.svg.png", orcamento: "R$ 600 Mi" },
            { nome: "Internacional", forca: 80, escudo: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Escudo_do_Sport_Club_Internacional.svg", orcamento: "R$ 450 Mi" },
            { nome: "Bahia", forca: 79, escudo: "https://upload.wikimedia.org/wikipedia/commons/2/20/Escudo_do_Esporte_Clube_Bahia.svg", orcamento: "R$ 400 Mi" },
            { nome: "Cruzeiro", forca: 79, escudo: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Escudo_do_Cruzeiro_Esporte_Clube.svg", orcamento: "R$ 350 Mi" },
            { nome: "Grêmio", forca: 78, escudo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Gr%C3%AAmio_FBPA.svg/1200px-Gr%C3%AAmio_FBPA.svg.png", orcamento: "R$ 500 Mi" },
            { nome: "Athletico-PR", forca: 78, escudo: "https://upload.wikimedia.org/wikipedia/commons/b/b3/CA_Paranaense.svg", orcamento: "R$ 300 Mi" },
            { nome: "Vasco", forca: 77, escudo: "https://upload.wikimedia.org/wikipedia/commons/6/67/Vasco_da_Gama_2021.png", orcamento: "R$ 300 Mi" },
            { nome: "Corinthians", forca: 77, escudo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Sport_Club_Corinthians_Paulista_crest.svg/1200px-Sport_Club_Corinthians_Paulista_crest.svg.png", orcamento: "R$ 700 Mi" },
            { nome: "Fluminense", forca: 77, escudo: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Fluminense_FC_escudo.png", orcamento: "R$ 400 Mi" },
            { nome: "Santos", forca: 76, escudo: "https://upload.wikimedia.org/wikipedia/commons/3/35/Santos_logo.svg", orcamento: "R$ 250 Mi" },
            { nome: "Bragantino", forca: 76, escudo: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Red_Bull_Bragantino.svg", orcamento: "R$ 300 Mi" },
            { nome: "Vitória", forca: 74, escudo: "https://upload.wikimedia.org/wikipedia/pt/6/6b/Esporte_Clube_Vit%C3%B3ria_logo.png", orcamento: "R$ 80 Mi" },
            { nome: "Mirassol", forca: 73, escudo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Mirassol_FC_logo.svg", orcamento: "R$ 60 Mi" },
            { nome: "Paysandu", forca: 72, escudo: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Paysandu_Sport_Club_logo.svg", orcamento: "R$ 50 Mi" },
            { nome: "Amazonas", forca: 71, escudo: "https://upload.wikimedia.org/wikipedia/pt/2/2c/Amazonas_fc_logo.png", orcamento: "R$ 40 Mi" },
            { nome: "Chapecoense", forca: 71, escudo: "https://upload.wikimedia.org/wikipedia/commons/3/37/Associa%C3%A7%C3%A3o_Chapecoense_de_Futebol_logo.svg", orcamento: "R$ 45 Mi" }
        ],
        // --- ACESSO (SÉRIE B) ---
        serieB: [
            { nome: "Fortaleza", forca: 78, escudo: "https://upload.wikimedia.org/wikipedia/commons/4/42/Fortaleza_Esporte_Clube_logo.svg", orcamento: "R$ 150 Mi" },
            { nome: "Ceará", forca: 77, escudo: "https://upload.wikimedia.org/wikipedia/commons/0/07/CearaSC.svg", orcamento: "R$ 120 Mi" },
            { nome: "Sport", forca: 76, escudo: "https://upload.wikimedia.org/wikipedia/commons/7/77/Sport_Club_do_Recife.svg", orcamento: "R$ 100 Mi" },
            { nome: "Juventude", forca: 75, escudo: "https://upload.wikimedia.org/wikipedia/commons/5/58/Esporte_Clube_Juventude_logo.svg", orcamento: "R$ 90 Mi" },
            { nome: "América-MG", forca: 74, escudo: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Am%C3%A9rica_Mineiro_logo.png", orcamento: "R$ 80 Mi" },
            { nome: "Goiás", forca: 74, escudo: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Goi%C3%A1s_Esporte_Clube_logo.svg", orcamento: "R$ 80 Mi" },
            { nome: "Atlético-GO", forca: 73, escudo: "https://upload.wikimedia.org/wikipedia/commons/9/93/Atl%C3%A9tico_Goianiense_new_logo.png", orcamento: "R$ 70 Mi" },
            { nome: "Coritiba", forca: 73, escudo: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Coritiba_FBC_%282024%29_-_Escudo.png", orcamento: "R$ 70 Mi" },
            { nome: "Cuiabá", forca: 73, escudo: "https://upload.wikimedia.org/wikipedia/commons/2/22/Cuiab%C3%A1_Esporte_Clube_logo.svg", orcamento: "R$ 65 Mi" },
            { nome: "Criciúma", forca: 72, escudo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Crici%C3%BAma_Esporte_Clube_logo.svg", orcamento: "R$ 60 Mi" },
            { nome: "Avaí", forca: 71, escudo: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Avai_FC_%2805-17%29.svg", orcamento: "R$ 50 Mi" },
            { nome: "Vila Nova", forca: 71, escudo: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Vila_Nova_Futebol_Clube_Logo.png", orcamento: "R$ 45 Mi" },
            { nome: "Novorizontino", forca: 70, escudo: "https://upload.wikimedia.org/wikipedia/commons/5/52/Gr%C3%AAmio_Novorizontino_logo.png", orcamento: "R$ 40 Mi" },
            { nome: "CRB", forca: 70, escudo: "https://upload.wikimedia.org/wikipedia/commons/8/87/Clube_de_Regatas_Brasil_logo.svg", orcamento: "R$ 40 Mi" },
            { nome: "Ponte Preta", forca: 69, escudo: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Ponte_Preta_logo.svg", orcamento: "R$ 35 Mi" },
            { nome: "Botafogo-SP", forca: 69, escudo: "https://upload.wikimedia.org/wikipedia/pt/e/e9/Botafogo_Futebol_Clube_logo.png", orcamento: "R$ 35 Mi" },
            { nome: "Operário-PR", forca: 68, escudo: "https://upload.wikimedia.org/wikipedia/commons/5/53/Oper%C3%A1rio_Ferrovi%C3%A1rio_Esporte_Clube_logo.svg", orcamento: "R$ 30 Mi" },
            { nome: "Náutico", forca: 68, escudo: "https://upload.wikimedia.org/wikipedia/commons/4/45/Clube_N%C3%A1utico_Capibaribe.svg", orcamento: "R$ 30 Mi" },
            { nome: "Londrina", forca: 67, escudo: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Londrina_Esporte_Clube.svg", orcamento: "R$ 25 Mi" },
            { nome: "São Bernardo", forca: 67, escudo: "https://upload.wikimedia.org/wikipedia/commons/e/ee/S%C3%A3o_Bernardo_Futebol_Clube_logo.svg", orcamento: "R$ 25 Mi" }
        ],
        // --- RAIZ (SÉRIE C) ---
        serieC: [
            { nome: "Guarani", forca: 68, escudo: "https://upload.wikimedia.org/wikipedia/commons/3/31/Escudo_do_Guarani_Futebol_Clube.svg", orcamento: "R$ 20 Mi" },
            { nome: "Ituano", forca: 67, escudo: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Ituano_Futebol_Clube_logo.png", orcamento: "R$ 18 Mi" },
            { nome: "Brusque", forca: 67, escudo: "https://upload.wikimedia.org/wikipedia/commons/2/23/Brusque_Futebol_Clube_logo.svg", orcamento: "R$ 18 Mi" },
            { nome: "Figueirense", forca: 66, escudo: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Figueirense_Futebol_Clube.svg", orcamento: "R$ 15 Mi" },
            { nome: "Remo", forca: 66, escudo: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Clube_do_Remo.svg", orcamento: "R$ 15 Mi" },
            { nome: "ABC", forca: 65, escudo: "https://upload.wikimedia.org/wikipedia/commons/3/30/ABC_FC_-_Escudo.png", orcamento: "R$ 12 Mi" },
            { nome: "CSA", forca: 65, escudo: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Centro_Sportivo_Alagoano_logo.svg", orcamento: "R$ 12 Mi" },
            { nome: "Sampaio Corrêa", forca: 64, escudo: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Sampaio_Corr%C3%AAa_Futebol_Clube_logo.svg", orcamento: "R$ 10 Mi" },
            { nome: "Volta Redonda", forca: 64, escudo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Volta_Redonda_Futebol_Clube_logo.svg", orcamento: "R$ 10 Mi" },
            { nome: "Ypiranga", forca: 64, escudo: "https://upload.wikimedia.org/wikipedia/commons/8/87/Ypiranga_Futebol_Clube_logo.svg", orcamento: "R$ 9 Mi" },
            { nome: "Caxias", forca: 63, escudo: "https://upload.wikimedia.org/wikipedia/commons/8/88/Sociedade_Esportiva_e_Recreativa_Caxias_do_Sul_logo.png", orcamento: "R$ 9 Mi" },
            { nome: "Confiança", forca: 63, escudo: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Associa%C3%A7%C3%A3o_Desportiva_Confian%C3%A7a_logo.svg", orcamento: "R$ 8 Mi" },
            { nome: "Ferroviário", forca: 62, escudo: "https://upload.wikimedia.org/wikipedia/commons/4/47/Ferrovi%C3%A1rio_Atl%C3%A9tico_Clube_logo.svg", orcamento: "R$ 8 Mi" },
            { nome: "Athletic-MG", forca: 62, escudo: "https://upload.wikimedia.org/wikipedia/commons/2/23/Athletic_Club_%28Minas_Gerais%29_logo.svg", orcamento: "R$ 8 Mi" },
            { nome: "Ferroviária", forca: 62, escudo: "https://upload.wikimedia.org/wikipedia/commons/7/77/Associa%C3%A7%C3%A3o_Ferrovi%C3%A1ria_de_Esportes_logo.svg", orcamento: "R$ 8 Mi" },
            { nome: "Floresta", forca: 61, escudo: "https://upload.wikimedia.org/wikipedia/commons/9/93/Floresta_Esporte_Clube_logo.svg", orcamento: "R$ 7 Mi" },
            { nome: "Retrô", forca: 61, escudo: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Retr%C3%B4_Futebol_Clube_Brasil_logo.png", orcamento: "R$ 7 Mi" },
            { nome: "Maringá", forca: 61, escudo: "https://upload.wikimedia.org/wikipedia/commons/9/91/Maringa_Futebol_Clube_logo.svg", orcamento: "R$ 6 Mi" },
            { nome: "Brasiliense", forca: 60, escudo: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Brasiliense_Futebol_Clube_logo.svg", orcamento: "R$ 6 Mi" },
            { nome: "Treze", forca: 60, escudo: "https://upload.wikimedia.org/wikipedia/commons/3/30/Treze_Futebol_Clube_logo.svg", orcamento: "R$ 5 Mi" }
        ],
        // --- BASE (SÉRIE D) ---
        serieD: [
            { nome: "Santa Cruz", forca: 60, escudo: "https://upload.wikimedia.org/wikipedia/commons/0/07/Santa_Cruz_Futebol_Clube.svg", orcamento: "R$ 5 Mi" },
            { nome: "Portuguesa", forca: 60, escudo: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Associa%C3%A7%C3%A3o_Portuguesa_de_Desportos.svg", orcamento: "R$ 5 Mi" },
            { nome: "Paraná", forca: 59, escudo: "https://upload.wikimedia.org/wikipedia/commons/0/02/Paran%C3%A1_Clube_logo.svg", orcamento: "R$ 4 Mi" },
            { nome: "Brasil de Pelotas", forca: 59, escudo: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Gr%C3%AAmio_Esportivo_Brasil_logo.svg", orcamento: "R$ 4 Mi" },
            { nome: "América-RN", forca: 59, escudo: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Am%C3%A9rica_de_Natal.svg", orcamento: "R$ 4 Mi" },
            { nome: "Nova Iguaçu", forca: 58, escudo: "https://upload.wikimedia.org/wikipedia/commons/d/d6/Nova_Igua%C3%A7u_Futebol_Clube_logo.svg", orcamento: "R$ 3 Mi" },
            { nome: "Água Santa", forca: 58, escudo: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Esporte_Clube_%C3%81gua_Santa_logo.svg", orcamento: "R$ 3 Mi" },
            { nome: "Portuguesa-RJ", forca: 58, escudo: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Associa%C3%A7%C3%A3o_Atl%C3%A9tica_Portuguesa_%28RJ%29_logo.svg", orcamento: "R$ 3 Mi" },
            { nome: "Campinense", forca: 58, escudo: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Campinense_Clube_logo.svg", orcamento: "R$ 3 Mi" },
            { nome: "Moto Club", forca: 57, escudo: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Moto_Club_de_S%C3%A3o_Lu%C3%ADs_logo.svg", orcamento: "R$ 2.5 Mi" },
            { nome: "River-PI", forca: 57, escudo: "https://upload.wikimedia.org/wikipedia/commons/3/30/River_Atl%C3%A9tico_Clube_logo.svg", orcamento: "R$ 2.5 Mi" },
            { nome: "Sergipe", forca: 57, escudo: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Club_Sportivo_Sergipe_logo.svg", orcamento: "R$ 2.5 Mi" },
            { nome: "ASA", forca: 57, escudo: "https://upload.wikimedia.org/wikipedia/commons/5/58/Agremia%C3%A7%C3%A3o_Sportiva_Arapiraquense_logo.svg", orcamento: "R$ 2.5 Mi" },
            { nome: "Inter de Limeira", forca: 57, escudo: "https://upload.wikimedia.org/wikipedia/commons/7/71/Associa%C3%A7%C3%A3o_Atl%C3%A9tica_Internacional_%28Limeira%29_logo.png", orcamento: "R$ 2.5 Mi" },
            { nome: "Hercílio Luz", forca: 57, escudo: "https://upload.wikimedia.org/wikipedia/commons/6/62/Herc%C3%ADlio_Luz_Futebol_Clube_logo.svg", orcamento: "R$ 2.5 Mi" },
            { nome: "Sousa", forca: 56, escudo: "https://upload.wikimedia.org/wikipedia/commons/d/de/Sousa_Esporte_Clube_logo.svg", orcamento: "R$ 2 Mi" },
            { nome: "Anápolis", forca: 56, escudo: "https://upload.wikimedia.org/wikipedia/commons/8/87/An%C3%A1polis_Futebol_Clube_logo.png", orcamento: "R$ 2 Mi" },
            { nome: "Manauara", forca: 56, escudo: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Manauara_Esporte_Clube_logo.svg", orcamento: "R$ 2 Mi" },
            { nome: "Cascavel", forca: 56, escudo: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Futebol_Clube_Cascavel_logo.svg", orcamento: "R$ 2 Mi" },
            { nome: "Cianorte", forca: 55, escudo: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Cianorte_Futebol_Clube_logo.png", orcamento: "R$ 1.5 Mi" }
        ]
            
    espanha: [
        { nome: "Real Madrid", forca: 92, escudo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/1200px-Real_Madrid_CF.svg.png", orcamento: "€ 800 Mi" },
        { nome: "Barcelona", forca: 89, escudo: "https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/1200px-FC_Barcelona_%28crest%29.svg.png", orcamento: "€ 700 Mi" },
        { nome: "Atlético Madrid", forca: 85, escudo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/Atletico_Madrid_2017_logo.svg/1200px-Atletico_Madrid_2017_logo.svg.png", orcamento: "€ 400 Mi" },
        { nome: "Sevilla", forca: 80, escudo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/Sevilla_FC_logo.svg/1200px-Sevilla_FC_logo.svg.png", orcamento: "€ 200 Mi" }
    ],
    inglaterra: [
        { nome: "Man City", forca: 94, escudo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png", orcamento: "£ 900 Mi" },
        { nome: "Liverpool", forca: 90, escudo: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/1200px-Liverpool_FC.svg.png", orcamento: "£ 800 Mi" },
        { nome: "Arsenal", forca: 89, escudo: "https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/1200px-Arsenal_FC.svg.png", orcamento: "£ 750 Mi" },
        { nome: "Chelsea", forca: 86, escudo: "https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/1200px-Chelsea_FC.svg.png", orcamento: "£ 600 Mi" }
    ],
    argentina: [
        { nome: "River Plate", forca: 82, escudo: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Logo_River_Plate.png", orcamento: "US$ 100 Mi" },
        { nome: "Boca Juniors", forca: 80, escudo: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Escudo_del_Club_Atl%C3%A9tico_Boca_Juniors_2012.svg", orcamento: "US$ 90 Mi" },
        { nome: "Racing", forca: 76, escudo: "https://upload.wikimedia.org/wikipedia/commons/5/56/Escudo_de_Racing_Club_2014.svg", orcamento: "US$ 50 Mi" },
        { nome: "Independiente", forca: 75, escudo: "https://upload.wikimedia.org/wikipedia/commons/d/db/Escudo_del_Club_Atl%C3%A9tico_Independiente.svg", orcamento: "US$ 40 Mi" }
    ]
};

// ELENCOS DETALHADOS
const PlayersDB = {
    "Flamengo": [
        { nome: "Rossi", pos: "GOL", forca: 81, idade: 30, carac: "Pegador de Pênaltis" },
        { nome: "Léo Ortiz", pos: "ZAG", forca: 83, idade: 30, carac: "Construtor" },
        { nome: "Léo Pereira", pos: "ZAG", forca: 80, idade: 30, carac: "Construtor" },
        { nome: "Vitão", pos: "ZAG", forca: 79, idade: 26, carac: "Xerife" },
        { nome: "Danilo", pos: "ZAG", forca: 81, idade: 34, carac: "Líder" },
        { nome: "Ayrton Lucas", pos: "LE", forca: 80, idade: 28, carac: "Veloz" },
        { nome: "Alex Sandro", pos: "LE", forca: 79, idade: 35, carac: "Apoio" },
        { nome: "Matías Viña", pos: "LE", forca: 79, idade: 28, carac: "Equilibrado" },
        { nome: "Emerson Royal", pos: "LD", forca: 81, idade: 27, carac: "Físico" },
        { nome: "Varela", pos: "LD", forca: 76, idade: 33, carac: "Defensivo" },
        { nome: "Erick Pulgar", pos: "VOL", forca: 81, idade: 32, carac: "Cão de Guarda" },
        { nome: "Jorginho", pos: "VOL", forca: 83, idade: 34, carac: "Maestro" },
        { nome: "Allan", pos: "VOL", forca: 77, idade: 29, carac: "Normal" },
        { nome: "De La Cruz", pos: "MEI", forca: 86, idade: 28, carac: "Incansável" },
        { nome: "Arrascaeta", pos: "MEI", forca: 87, idade: 31, carac: "Maestro" },
        { nome: "Saúl Ñíguez", pos: "MEI", forca: 82, idade: 31, carac: "Versátil" },
        { nome: "Jorge Carrascal", pos: "MEI", forca: 79, idade: 27, carac: "Driblador" },
        { nome: "Pedro", pos: "ATA", forca: 86, idade: 28, carac: "Artilheiro" },
        { nome: "Samuel Lino", pos: "ATA", forca: 84, idade: 26, carac: "Veloz" },
        { nome: "Everton Cebolinha", pos: "ATA", forca: 82, idade: 29, carac: "Infiltrador" },
        { nome: "Bruno Henrique", pos: "ATA", forca: 80, idade: 35, carac: "Veloz" },
        { nome: "Gonzalo Plata", pos: "ATA", forca: 79, idade: 25, carac: "Habilidoso" },
        { nome: "Luiz Araújo", pos: "ATA", forca: 79, idade: 29, carac: "Chute de Longe" },
        { nome: "Michael", pos: "ATA", forca: 78, idade: 29, carac: "Liso" }
    ],
    "Palmeiras": [
        { nome: "Weverton", pos: "GOL", forca: 83, idade: 38, carac: "Líder" },
        { nome: "Carlos Miguel", pos: "GOL", forca: 81, idade: 27, carac: "Paredão" },
        { nome: "Marcelo Lomba", pos: "GOL", forca: 76, idade: 39, carac: "Normal" },
        { nome: "Gustavo Gómez", pos: "ZAG", forca: 85, idade: 32, carac: "Xerife" },
        { nome: "Murilo", pos: "ZAG", forca: 83, idade: 28, carac: "Artilheiro" },
        { nome: "Bruno Fuchs", pos: "ZAG", forca: 79, idade: 26, carac: "Construtor" },
        { nome: "Vitor Reis", pos: "ZAG", forca: 77, idade: 20, carac: "Veloz" },
        { nome: "Agustín Giay", pos: "LD", forca: 78, idade: 22, carac: "Apoio" },
        { nome: "Khellven", pos: "LD", forca: 77, idade: 24, carac: "Cruzador" },
        { nome: "Piquerez", pos: "LE", forca: 84, idade: 27, carac: "Equilibrado" },
        { nome: "Jefté", pos: "LE", forca: 76, idade: 22, carac: "Ofensivo" },
        { nome: "Marlon Freitas", pos: "VOL", forca: 80, idade: 30, carac: "Maestro" },
        { nome: "Allan", pos: "VOL", forca: 80, idade: 22, carac: "Cão de Guarda" },
        { nome: "Fabinho", pos: "VOL", forca: 75, idade: 23, carac: "Normal" },
        { nome: "Andreas Pereira", pos: "MEI", forca: 86, idade: 30, carac: "Bola Parada" },
        { nome: "Raphael Veiga", pos: "MEI", forca: 85, idade: 30, carac: "Decisivo" },
        { nome: "Maurício", pos: "MEI", forca: 81, idade: 24, carac: "Habilidoso" },
        { nome: "Lucas Evangelista", pos: "MEI", forca: 78, idade: 30, carac: "Incansável" },
        { nome: "Felipe Anderson", pos: "ATA", forca: 83, idade: 32, carac: "Driblador" },
        { nome: "Facundo Torres", pos: "ATA", forca: 80, idade: 25, carac: "Chute de Longe" },
        { nome: "Ramón Sosa", pos: "ATA", forca: 81, idade: 26, carac: "Veloz" },
        { nome: "Paulinho", pos: "ATA", forca: 82, idade: 25, carac: "Artilheiro" },
        { nome: "Vitor Roque", pos: "ATA", forca: 85, idade: 20, carac: "Infiltrador" },
        { nome: "Flaco López", pos: "ATA", forca: 82, idade: 25, carac: "Cabeceador" }
    ],
    "Atlético-MG": [
        { nome: "Everson", pos: "GOL", forca: 80, idade: 35, carac: "Paredão" },
        { nome: "Matheus Mendes", pos: "GOL", forca: 77, idade: 27, carac: "Pegador de Pênaltis" },
        { nome: "Junior Alonso", pos: "ZAG", forca: 81, idade: 33, carac: "Xerife" },
        { nome: "Lyanco", pos: "ZAG", forca: 80, idade: 29, carac: "Físico" },
        { nome: "Igor Rabello", pos: "ZAG", forca: 76, idade: 30, carac: "Normal" },
        { nome: "Mauricio Lemos", pos: "ZAG", forca: 76, idade: 30, carac: "Bola Parada" },
        { nome: "Guilherme Arana", pos: "LE", forca: 84, idade: 28, carac: "Apoio" },
        { nome: "Rubens", pos: "LE", forca: 78, idade: 24, carac: "Versátil" },
        { nome: "Renzo Saravia", pos: "LD", forca: 76, idade: 32, carac: "Defensivo" },
        { nome: "Mariano", pos: "LD", forca: 74, idade: 39, carac: "Líder" },
        { nome: "Otávio", pos: "VOL", forca: 79, idade: 31, carac: "Cão de Guarda" },
        { nome: "Fausto Vera", pos: "VOL", forca: 80, idade: 25, carac: "Equilibrado" },
        { nome: "Alan Franco", pos: "VOL", forca: 78, idade: 27, carac: "Incansável" },
        { nome: "Matías Zaracho", pos: "MEI", forca: 82, idade: 27, carac: "Infiltrador" },
        { nome: "Gustavo Scarpa", pos: "MEI", forca: 83, idade: 32, carac: "Chute de Longe" },
        { nome: "Bernard", pos: "MEI", forca: 78, idade: 33, carac: "Habilidoso" },
        { nome: "Igor Gomes", pos: "MEI", forca: 76, idade: 26, carac: "Construtor" },
        { nome: "Hulk", pos: "ATA", forca: 83, idade: 39, carac: "Canhão" },
        { nome: "Arthur Cabral", pos: "ATA", forca: 82, idade: 27, carac: "Pivô" },
        { nome: "Deyverson", pos: "ATA", forca: 77, idade: 34, carac: "Raçudo" },
        { nome: "Alisson", pos: "ATA", forca: 78, idade: 20, carac: "Veloz" },
        { nome: "Cadu", pos: "ATA", forca: 76, idade: 21, carac: "Finalizador" },
        { nome: "Talles Magno", pos: "ATA", forca: 79, idade: 23, carac: "Driblador" },
        { nome: "Brahian Palacios", pos: "ATA", forca: 75, idade: 23, carac: "Veloz" }
    ],
    "São Paulo": [
        { nome: "Rafael", pos: "GOL", forca: 81, idade: 36, carac: "Paredão" },
        { nome: "Jandrei", pos: "GOL", forca: 75, idade: 32, carac: "Joga com os Pés" },
        { nome: "Arboleda", pos: "ZAG", forca: 81, idade: 34, carac: "Xerife" },
        { nome: "Alan Franco", pos: "ZAG", forca: 80, idade: 29, carac: "Construtor" },
        { nome: "Ferraresi", pos: "ZAG", forca: 79, idade: 27, carac: "Técnico" },
        { nome: "Sabino", pos: "ZAG", forca: 76, idade: 29, carac: "Canhoto" },
        { nome: "Wendell", pos: "LE", forca: 80, idade: 32, carac: "Equilibrado" },
        { nome: "Patryck", pos: "LE", forca: 75, idade: 23, carac: "Ofensivo" },
        { nome: "Igor Vinícius", pos: "LD", forca: 78, idade: 28, carac: "Veloz" },
        { nome: "Moreira", pos: "LD", forca: 76, idade: 21, carac: "Promessa" },
        { nome: "Pablo Maia", pos: "VOL", forca: 82, idade: 24, carac: "Chute de Longe" },
        { nome: "Bobadilla", pos: "VOL", forca: 78, idade: 24, carac: "Infiltrador" },
        { nome: "Marcos Antônio", pos: "VOL", forca: 79, idade: 25, carac: "Dinâmico" },
        { nome: "Pol Fernández", pos: "VOL", forca: 79, idade: 34, carac: "Líder" },
        { nome: "Alisson", pos: "MEI", forca: 80, idade: 32, carac: "Incansável" },
        { nome: "Rodrigo Nestor", pos: "MEI", forca: 79, idade: 25, carac: "Decisivo" },
        { nome: "Galoppo", pos: "MEI", forca: 78, idade: 26, carac: "Finalizador" },
        { nome: "Lucas Moura", pos: "MEI", forca: 84, idade: 33, carac: "Craque" },
        { nome: "Luciano", pos: "ATA", forca: 81, idade: 32, carac: "Raçudo" },
        { nome: "Calleri", pos: "ATA", forca: 83, idade: 32, carac: "Toca no Calleri" },
        { nome: "Ferreirinha", pos: "ATA", forca: 80, idade: 28, carac: "Driblador" },
        { nome: "William Gomes", pos: "ATA", forca: 79, idade: 20, carac: "Veloz" },
        { nome: "André Silva", pos: "ATA", forca: 78, idade: 28, carac: "Pivô" },
        { nome: "Henrique Carmo", pos: "ATA", forca: 75, idade: 19, carac: "Liso" }
    ],
    "Corinthians": [
        { nome: "Hugo Souza", pos: "GOL", forca: 82, idade: 27, carac: "Paredão" },
        { nome: "Matheus Donelli", pos: "GOL", forca: 76, idade: 24, carac: "Promessa" },
        { nome: "André Ramalho", pos: "ZAG", forca: 81, idade: 34, carac: "Líder" },
        { nome: "Félix Torres", pos: "ZAG", forca: 79, idade: 29, carac: "Veloz" },
        { nome: "Gustavo Henrique", pos: "ZAG", forca: 78, idade: 33, carac: "Bola Aérea" },
        { nome: "Cacá", pos: "ZAG", forca: 77, idade: 27, carac: "Impulsivo" },
        { nome: "Fabrizio Angileri", pos: "LE", forca: 79, idade: 32, carac: "Equilibrado" },
        { nome: "Matheus Bidu", pos: "LE", forca: 76, idade: 27, carac: "Apoio" },
        { nome: "Matheuzinho", pos: "LD", forca: 78, idade: 26, carac: "Ofensivo" },
        { nome: "Fagner", pos: "LD", forca: 77, idade: 36, carac: "Experiente" },
        { nome: "José Martínez", pos: "VOL", forca: 80, idade: 31, carac: "Cão de Guarda" },
        { nome: "Charles", pos: "VOL", forca: 78, idade: 30, carac: "Versátil" },
        { nome: "Alex Santana", pos: "VOL", forca: 79, idade: 31, carac: "Físico" },
        { nome: "Breno Bidon", pos: "VOL", forca: 78, idade: 21, carac: "Maestro" },
        { nome: "Maycon", pos: "MEI", forca: 79, idade: 29, carac: "Equilibrado" },
        { nome: "Rodrigo Garro", pos: "MEI", forca: 84, idade: 28, carac: "Craque" },
        { nome: "Igor Coronado", pos: "MEI", forca: 81, idade: 33, carac: "Habilidoso" },
        { nome: "André Carrillo", pos: "MEI", forca: 80, idade: 34, carac: "Driblador" },
        { nome: "Memphis Depay", pos: "ATA", forca: 85, idade: 32, carac: "Estrela" },
        { nome: "Yuri Alberto", pos: "ATA", forca: 82, idade: 25, carac: "Artilheiro" },
        { nome: "Talles Magno", pos: "ATA", forca: 79, idade: 24, carac: "Liso" },
        { nome: "Pedro Raul", pos: "ATA", forca: 77, idade: 29, carac: "Pivô" },
        { nome: "Héctor Hernández", pos: "ATA", forca: 76, idade: 30, carac: "Finalizador" },
        { nome: "Gui Negão", pos: "ATA", forca: 74, idade: 19, carac: "Promessa" }
    ],
    "Fluminense": [
        { nome: "Fábio", pos: "GOL", forca: 79, idade: 45, carac: "Experiente" },
        { nome: "Vitor Eudes", pos: "GOL", forca: 75, idade: 27, carac: "Pegador de Pênaltis" },
        { nome: "Thiago Silva", pos: "ZAG", forca: 79, idade: 41, carac: "Líder" },
        { nome: "Ignácio", pos: "ZAG", forca: 78, idade: 29, carac: "Bola Aérea" },
        { nome: "Thiago Santos", pos: "ZAG", forca: 76, idade: 36, carac: "Força" },
        { nome: "Igor Rabello", pos: "ZAG", forca: 77, idade: 30, carac: "Normal" },
        { nome: "Gabriel Fuentes", pos: "LE", forca: 78, idade: 29, carac: "Apoio" },
        { nome: "Esquerdinha", pos: "LE", forca: 74, idade: 20, carac: "Promessa" },
        { nome: "Samuel Xavier", pos: "LD", forca: 76, idade: 35, carac: "Equilibrado" },
        { nome: "Guga", pos: "LD", forca: 75, idade: 27, carac: "Apoio" },
        { nome: "Martinelli", pos: "VOL", forca: 80, idade: 24, carac: "Dinâmico" },
        { nome: "Facundo Bernal", pos: "VOL", forca: 79, idade: 22, carac: "Cão de Guarda" },
        { nome: "Nonato", pos: "VOL", forca: 76, idade: 28, carac: "Construtor" },
        { nome: "Ganso", pos: "MEI", forca: 80, idade: 36, carac: "Maestro" },
        { nome: "Lucho Acosta", pos: "MEI", forca: 82, idade: 31, carac: "Driblador" },
        { nome: "Lima", pos: "MEI", forca: 77, idade: 29, carac: "Versátil" },
        { nome: "Renato Augusto", pos: "MEI", forca: 75, idade: 38, carac: "Passe Final" },
        { nome: "Germán Cano", pos: "ATA", forca: 81, idade: 38, carac: "Finalizador" },
        { nome: "Soteldo", pos: "ATA", forca: 81, idade: 28, carac: "Liso" },
        { nome: "Kevin Serna", pos: "ATA", forca: 79, idade: 28, carac: "Veloz" },
        { nome: "Agustín Canobbio", pos: "ATA", forca: 80, idade: 27, carac: "Incansável" },
        { nome: "John Kennedy", pos: "ATA", forca: 78, idade: 23, carac: "Decisivo" },
        { nome: "Kauã Elias", pos: "ATA", forca: 77, idade: 20, carac: "Artilheiro" },
        { nome: "Riquelme Felipe", pos: "ATA", forca: 74, idade: 19, carac: "Habilidoso" }
    ],
    "Grêmio": [
        { nome: "Tiago Volpi", pos: "GOL", forca: 79, idade: 35, carac: "Pegador de Pênaltis" },
        { nome: "Gabriel Grando", pos: "GOL", forca: 75, idade: 26, carac: "Normal" },
        { nome: "Kannemann", pos: "ZAG", forca: 80, idade: 35, carac: "Xerife" },
        { nome: "Fabián Balbuena", pos: "ZAG", forca: 79, idade: 34, carac: "Líder" },
        { nome: "Jemerson", pos: "ZAG", forca: 78, idade: 33, carac: "Bola Aérea" },
        { nome: "Gustavo Martins", pos: "ZAG", forca: 77, idade: 23, carac: "Veloz" },
        { nome: "Rodrigo Ely", pos: "ZAG", forca: 76, idade: 32, carac: "Físico" },
        { nome: "Marlon", pos: "LE", forca: 79, idade: 28, carac: "Equilibrado" },
        { nome: "Mayk", pos: "LE", forca: 74, idade: 26, carac: "Apoio" },
        { nome: "João Pedro", pos: "LD", forca: 78, idade: 29, carac: "Ofensivo" },
        { nome: "Marcos Rocha", pos: "LD", forca: 75, idade: 37, carac: "Experiente" },
        { nome: "Villasanti", pos: "VOL", forca: 82, idade: 29, carac: "Incansável" },
        { nome: "Dodi", pos: "VOL", forca: 77, idade: 30, carac: "Dinâmico" },
        { nome: "Gustavo Cuéllar", pos: "VOL", forca: 79, idade: 33, carac: "Cão de Guarda" },
        { nome: "Arthur", pos: "MEI", forca: 81, idade: 29, carac: "Maestro" },
        { nome: "Franco Cristaldo", pos: "MEI", forca: 81, idade: 29, carac: "Passe Final" },
        { nome: "Miguel Monsalve", pos: "MEI", forca: 78, idade: 22, carac: "Habilidoso" },
        { nome: "Edenilson", pos: "MEI", forca: 75, idade: 36, carac: "Infiltrador" },
        { nome: "Martin Braithwaite", pos: "ATA", forca: 82, idade: 34, carac: "Artilheiro" },
        { nome: "Cristian Pavon", pos: "ATA", forca: 79, idade: 30, carac: "Veloz" },
        { nome: "Alexander Aravena", pos: "ATA", forca: 78, idade: 23, carac: "Driblador" },
        { nome: "Gabriel Mec", pos: "ATA", forca: 76, idade: 18, carac: "Promessa" },
        { nome: "André Henrique", pos: "ATA", forca: 75, idade: 24, carac: "Pivô" },
        { nome: "Diego Costa", pos: "ATA", forca: 78, idade: 37, carac: "Raçudo" }
    ],
    "Internacional": [
        { nome: "Rochet", pos: "GOL", forca: 82, idade: 33, carac: "Líder" },
        { nome: "Ivan", pos: "GOL", forca: 76, idade: 28, carac: "Pegador de Pênaltis" },
        { nome: "Juan Jesus", pos: "ZAG", forca: 80, idade: 34, carac: "Xerife" },
        { nome: "Agustín Rogel", pos: "ZAG", forca: 78, idade: 28, carac: "Físico" },
        { nome: "Gabriel Mercado", pos: "ZAG", forca: 75, idade: 39, carac: "Experiente" },
        { nome: "Igor Gomes", pos: "ZAG", forca: 75, idade: 25, carac: "Veloz" },
        { nome: "Bernabei", pos: "LE", forca: 79, idade: 25, carac: "Apoio" },
        { nome: "Renê", pos: "LE", forca: 75, idade: 33, carac: "Equilibrado" },
        { nome: "Braian Aguirre", pos: "LD", forca: 77, idade: 25, carac: "Ofensivo" },
        { nome: "Nathan", pos: "LD", forca: 74, idade: 24, carac: "Apoio" },
        { nome: "Fernando", pos: "VOL", forca: 79, idade: 38, carac: "Cão de Guarda" },
        { nome: "Thiago Maia", pos: "VOL", forca: 79, idade: 29, carac: "Equilibrado" },
        { nome: "Bruno Henrique", pos: "VOL", forca: 77, idade: 36, carac: "Dinâmico" },
        { nome: "Rômulo", pos: "VOL", forca: 76, idade: 26, carac: "Versátil" },
        { nome: "Oscar", pos: "MEI", forca: 82, idade: 34, carac: "Maestro" },
        { nome: "Alan Patrick", pos: "MEI", forca: 81, idade: 34, carac: "Passe Final" },
        { nome: "Bruno Tabata", pos: "MEI", forca: 78, idade: 29, carac: "Chute de Longe" },
        { nome: "Gabriel Carvalho", pos: "MEI", forca: 79, idade: 18, carac: "Promessa" },
        { nome: "Rafael Borré", pos: "ATA", forca: 81, idade: 30, carac: "Raçudo" },
        { nome: "Enner Valencia", pos: "ATA", forca: 80, idade: 36, carac: "Finalizador" },
        { nome: "Wanderson", pos: "ATA", forca: 78, idade: 31, carac: "Driblador" },
        { nome: "Wesley", pos: "ATA", forca: 77, idade: 27, carac: "Liso" },
        { nome: "Lucas Alario", pos: "ATA", forca: 77, idade: 33, carac: "Cabeceador" },
        { nome: "Ricardo Mathias", pos: "ATA", forca: 74, idade: 20, carac: "Pivô" }
    ],
    "Botafogo": [
        { nome: "John", pos: "GOL", forca: 81, idade: 30, carac: "Paredão" },
        { nome: "Gatito Fernández", pos: "GOL", forca: 75, idade: 38, carac: "Líder" },
        { nome: "Alexander Barboza", pos: "ZAG", forca: 80, idade: 31, carac: "Xerife" },
        { nome: "Bastos", pos: "ZAG", forca: 78, idade: 34, carac: "Físico" },
        { nome: "Lucas Halter", pos: "ZAG", forca: 76, idade: 26, carac: "Bola Aérea" },
        { nome: "Adryelson", pos: "ZAG", forca: 79, idade: 28, carac: "Veloz" },
        { nome: "Alex Telles", pos: "LE", forca: 80, idade: 33, carac: "Bola Parada" },
        { nome: "Cuiabano", pos: "LE", forca: 77, idade: 23, carac: "Ofensivo" },
        { nome: "Vitinho", pos: "LD", forca: 78, idade: 26, carac: "Apoio" },
        { nome: "Mateo Ponte", pos: "LD", forca: 75, idade: 23, carac: "Equilibrado" },
        { nome: "Gregore", pos: "VOL", forca: 79, idade: 32, carac: "Cão de Guarda" },
        { nome: "Walace", pos: "VOL", forca: 79, idade: 31, carac: "Físico" },
        { nome: "Danilo Barbosa", pos: "VOL", forca: 77, idade: 30, carac: "Chute de Longe" },
        { nome: "Tchê Tchê", pos: "VOL", forca: 76, idade: 33, carac: "Incansável" },
        { nome: "Thiago Almada", pos: "MEI", forca: 84, idade: 25, carac: "Craque" },
        { nome: "Eduardo", pos: "MEI", forca: 76, idade: 36, carac: "Técnico" },
        { nome: "Savarino", pos: "ATA", forca: 79, idade: 29, carac: "Habilidoso" },
        { nome: "Luiz Henrique", pos: "ATA", forca: 83, idade: 25, carac: "Driblador" },
        { nome: "Igor Jesus", pos: "ATA", forca: 81, idade: 25, carac: "Artilheiro" },
        { nome: "Tiquinho Soares", pos: "ATA", forca: 78, idade: 35, carac: "Pivô" },
        { nome: "Júnior Santos", pos: "ATA", forca: 78, idade: 31, carac: "Veloz" },
        { nome: "Matheus Martins", pos: "ATA", forca: 78, idade: 22, carac: "Liso" },
        { nome: "Jeffinho", pos: "ATA", forca: 77, idade: 26, carac: "Infiltrador" },
        { nome: "Carlos Alberto", pos: "ATA", forca: 74, idade: 24, carac: "Veloz" }
    ],
    "Vasco": [
        { nome: "Léo Jardim", pos: "GOL", forca: 80, idade: 31, carac: "Paredão" },
        { nome: "Keiller", pos: "GOL", forca: 74, idade: 29, carac: "Normal" },
        { nome: "João Victor", pos: "ZAG", forca: 80, idade: 27, carac: "Veloz" },
        { nome: "Léo", pos: "ZAG", forca: 76, idade: 30, carac: "Construtor" },
        { nome: "Maicon", pos: "ZAG", forca: 74, idade: 37, carac: "Líder" },
        { nome: "Robert Renan", pos: "ZAG", forca: 78, idade: 22, carac: "Promessa" },
        { nome: "Lucas Piton", pos: "LE", forca: 79, idade: 25, carac: "Cruzador" },
        { nome: "Victor Luis", pos: "LE", forca: 73, idade: 32, carac: "Bola Parada" },
        { nome: "Puma Rodríguez", pos: "LD", forca: 75, idade: 29, carac: "Ofensivo" },
        { nome: "Paulo Henrique", pos: "LD", forca: 75, idade: 29, carac: "Veloz" },
        { nome: "Hugo Moura", pos: "VOL", forca: 77, idade: 28, carac: "Cão de Guarda" },
        { nome: "Jair", pos: "VOL", forca: 78, idade: 31, carac: "Maestro" },
        { nome: "Mateus Carvalho", pos: "VOL", forca: 76, idade: 24, carac: "Físico" },
        { nome: "Souza", pos: "VOL", forca: 74, idade: 37, carac: "Experiente" },
        { nome: "Philippe Coutinho", pos: "MEI", forca: 81, idade: 34, carac: "Craque" },
        { nome: "Paulinho Paula", pos: "MEI", forca: 79, idade: 29, carac: "Dinâmico" },
        { nome: "Dimitri Payet", pos: "MEI", forca: 78, idade: 39, carac: "Passe Final" },
        { nome: "Maxime Dominguez", pos: "MEI", forca: 75, idade: 30, carac: "Técnico" },
        { nome: "Pablo Vegetti", pos: "ATA", forca: 78, idade: 38, carac: "Cabeceador" },
        { nome: "David", pos: "ATA", forca: 77, idade: 30, carac: "Físico" },
        { nome: "Adson", pos: "ATA", forca: 77, idade: 25, carac: "Driblador" },
        { nome: "Brian Rodríguez", pos: "ATA", forca: 78, idade: 26, carac: "Veloz" },
        { nome: "Rayan", pos: "ATA", forca: 76, idade: 19, carac: "Promessa" },
        { nome: "Emerson Rodríguez", pos: "ATA", forca: 75, idade: 25, carac: "Liso" }
    ],
    "Cruzeiro": [
        { nome: "Cássio", pos: "GOL", forca: 81, idade: 38, carac: "Líder" },
        { nome: "Anderson", pos: "GOL", forca: 75, idade: 27, carac: "Normal" },
        { nome: "Zé Ivaldo", pos: "ZAG", forca: 79, idade: 28, carac: "Físico" },
        { nome: "João Marcelo", pos: "ZAG", forca: 78, idade: 25, carac: "Bola Aérea" },
        { nome: "Lucas Villalba", pos: "ZAG", forca: 76, idade: 31, carac: "Construtor" },
        { nome: "Marlon", pos: "LE", forca: 80, idade: 28, carac: "Equilibrado" },
        { nome: "Kaiki Bruno", pos: "LE", forca: 74, idade: 22, carac: "Promessa" },
        { nome: "William", pos: "LD", forca: 81, idade: 30, carac: "Apoio" },
        { nome: "Wesley Gasolina", pos: "LD", forca: 74, idade: 25, carac: "Veloz" },
        { nome: "Matheus Henrique", pos: "VOL", forca: 80, idade: 28, carac: "Dinâmico" },
        { nome: "Lucas Romero", pos: "VOL", forca: 78, idade: 31, carac: "Cão de Guarda" },
        { nome: "Lucas Silva", pos: "VOL", forca: 76, idade: 32, carac: "Líder" },
        { nome: "Fabrizio Peralta", pos: "VOL", forca: 76, idade: 23, carac: "Versátil" },
        { nome: "Matheus Pereira", pos: "MEI", forca: 84, idade: 29, carac: "Craque" },
        { nome: "Barreal", pos: "MEI", forca: 77, idade: 25, carac: "Chute de Longe" },
        { nome: "Mateus Vital", pos: "MEI", forca: 75, idade: 27, carac: "Técnico" },
        { nome: "Gabigol", pos: "ATA", forca: 83, idade: 29, carac: "Decisivo" },
        { nome: "Kaio Jorge", pos: "ATA", forca: 79, idade: 24, carac: "Pivô" },
        { nome: "Gabriel Veron", pos: "ATA", forca: 78, idade: 23, carac: "Veloz" },
        { nome: "Lautaro Díaz", pos: "ATA", forca: 78, idade: 27, carac: "Infiltrador" },
        { nome: "Juan Dinenno", pos: "ATA", forca: 77, idade: 31, carac: "Cabeceador" },
        { nome: "Rafa Silva", pos: "ATA", forca: 75, idade: 33, carac: "Finalizador" }
    ],
    "Bahia": [
        { nome: "Marcos Felipe", pos: "GOL", forca: 79, idade: 29, carac: "Pegador de Pênaltis" },
        { nome: "Adriel", pos: "GOL", forca: 74, idade: 25, carac: "Normal" },
        { nome: "Gabriel Xavier", pos: "ZAG", forca: 79, idade: 24, carac: "Veloz" },
        { nome: "Kanu", pos: "ZAG", forca: 78, idade: 28, carac: "Líder" },
        { nome: "Víctor Cuesta", pos: "ZAG", forca: 76, idade: 37, carac: "Experiente" },
        { nome: "David Duarte", pos: "ZAG", forca: 74, idade: 30, carac: "Bola Aérea" },
        { nome: "Luciano Juba", pos: "LE", forca: 78, idade: 26, carac: "Chute de Longe" },
        { nome: "Iago Borduchi", pos: "LE", forca: 77, idade: 28, carac: "Apoio" },
        { nome: "Santiago Arias", pos: "LD", forca: 79, idade: 34, carac: "Equilibrado" },
        { nome: "Gilberto", pos: "LD", forca: 76, idade: 32, carac: "Ofensivo" },
        { nome: "Caio Alexandre", pos: "VOL", forca: 80, idade: 26, carac: "Maestro" },
        { nome: "Jean Lucas", pos: "VOL", forca: 79, idade: 27, carac: "Dinâmico" },
        { nome: "Rezende", pos: "VOL", forca: 76, idade: 30, carac: "Cão de Guarda" },
        { nome: "Everton Ribeiro", pos: "MEI", forca: 81, idade: 36, carac: "Craque" },
        { nome: "Cauly", pos: "MEI", forca: 82, idade: 30, carac: "Driblador" },
        { nome: "Thaciano", pos: "MEI", forca: 78, idade: 30, carac: "Versátil" },
        { nome: "Luciano Rodríguez", pos: "ATA", forca: 81, idade: 22, carac: "Habilidoso" },
        { nome: "Biel", pos: "ATA", forca: 78, idade: 24, carac: "Liso" },
        { nome: "Ademir", pos: "ATA", forca: 77, idade: 30, carac: "Veloz" },
        { nome: "Everaldo", pos: "ATA", forca: 76, idade: 34, carac: "Raçudo" },
        { nome: "Rafael Ratão", pos: "ATA", forca: 75, idade: 30, carac: "Físico" },
        { nome: "Tiago", pos: "ATA", forca: 74, idade: 24, carac: "Promessa" }
    ],
    "Fortaleza": [
        { nome: "João Ricardo", pos: "GOL", forca: 80, idade: 37, carac: "Paredão" },
        { nome: "Santos", pos: "GOL", forca: 76, idade: 35, carac: "Seguro" },
        { nome: "Tomás Cardona", pos: "ZAG", forca: 77, idade: 30, carac: "Físico" },
        { nome: "Kuscevic", pos: "ZAG", forca: 77, idade: 29, carac: "Xerife" },
        { nome: "Brítez", pos: "ZAG", forca: 78, idade: 29, carac: "Versátil" },
        { nome: "Titi", pos: "ZAG", forca: 74, idade: 37, carac: "Líder" },
        { nome: "Bruno Pacheco", pos: "LE", forca: 77, idade: 34, carac: "Equilibrado" },
        { nome: "Felipe Jonatan", pos: "LE", forca: 76, idade: 27, carac: "Técnico" },
        { nome: "Tinga", pos: "LD", forca: 79, idade: 32, carac: "Incansável" },
        { nome: "Eros Mancuso", pos: "LD", forca: 76, idade: 26, carac: "Apoio" },
        { nome: "Hércules", pos: "VOL", forca: 80, idade: 25, carac: "Dinâmico" },
        { nome: "Zé Welison", pos: "VOL", forca: 76, idade: 30, carac: "Chute de Longe" },
        { nome: "Lucas Sasha", pos: "VOL", forca: 75, idade: 35, carac: "Cão de Guarda" },
        { nome: "Pochettino", pos: "MEI", forca: 81, idade: 29, carac: "Passe Final" },
        { nome: "Kervin Andrade", pos: "MEI", forca: 78, idade: 20, carac: "Driblador" },
        { nome: "Calebe", pos: "MEI", forca: 76, idade: 25, carac: "Habilidoso" },
        { nome: "Lucero", pos: "ATA", forca: 82, idade: 34, carac: "Artilheiro" },
        { nome: "Moisés", pos: "ATA", forca: 79, idade: 29, carac: "Veloz" },
        { nome: "Yago Pikachu", pos: "ATA", forca: 78, idade: 33, carac: "Infiltrador" },
        { nome: "Marinho", pos: "ATA", forca: 77, idade: 35, carac: "Canhão" },
        { nome: "Breno Lopes", pos: "ATA", forca: 76, idade: 29, carac: "Decisivo" },
        { nome: "Renato Kayzer", pos: "ATA", forca: 75, idade: 29, carac: "Raçudo" }
    ],
    "Athletico-PR": [
        { nome: "Mycael", pos: "GOL", forca: 78, idade: 21, carac: "Pegador de Pênaltis" },
        { nome: "Léo Linck", pos: "GOL", forca: 75, idade: 24, carac: "Seguro" },
        { nome: "Thiago Heleno", pos: "ZAG", forca: 78, idade: 37, carac: "Xerife" },
        { nome: "Kaique Rocha", pos: "ZAG", forca: 79, idade: 24, carac: "Veloz" },
        { nome: "Gamarra", pos: "ZAG", forca: 76, idade: 25, carac: "Físico" },
        { nome: "Esquivel", pos: "LE", forca: 79, idade: 30, carac: "Cruzador" },
        { nome: "Fernando", pos: "LE", forca: 75, idade: 26, carac: "Equilibrado" },
        { nome: "Léo Godoy", pos: "LD", forca: 76, idade: 30, carac: "Apoio" },
        { nome: "Madson", pos: "LD", forca: 74, idade: 34, carac: "Veloz" },
        { nome: "Erick", pos: "VOL", forca: 79, idade: 28, carac: "Versátil" },
        { nome: "Gabriel", pos: "VOL", forca: 77, idade: 33, carac: "Cão de Guarda" },
        { nome: "Felipinho", pos: "VOL", forca: 75, idade: 24, carac: "Dinâmico" },
        { nome: "Bruno Zapelli", pos: "MEI", forca: 81, idade: 23, carac: "Maestro" },
        { nome: "Nikão", pos: "MEI", forca: 76, idade: 33, carac: "Chute de Longe" },
        { nome: "Praxedes", pos: "MEI", forca: 75, idade: 23, carac: "Técnico" },
        { nome: "Mastriani", pos: "ATA", forca: 80, idade: 32, carac: "Cabeceador" },
        { nome: "Cuello", pos: "ATA", forca: 78, idade: 26, carac: "Chute de Longe" },
        { nome: "Pablo", pos: "ATA", forca: 77, idade: 33, carac: "Pivô" },
        { nome: "Julimar", pos: "ATA", forca: 76, idade: 24, carac: "Físico" },
        { nome: "Emersonn", pos: "ATA", forca: 74, idade: 21, carac: "Promessa" },
        { nome: "Di Yorio", pos: "ATA", forca: 75, idade: 29, carac: "Raçudo" }
    ]
};
